### PR TITLE
Core/Template: Allow to store items for different item set templates …

### PR DESCRIPTION
**Pull request by robinsch**
…and add them to character with TemplateMgr::AddItems method.

Can be used for testing purpose. (Allows faster gearing for new chars)

### CODE REVIEW

**Comment by DevDaemon** [comment]
Why don't you use the npc_welcome script?

**Comment by robinsch** [comment]
Using the script for what?

**Comment by DevDaemon** [comment]
For testing purposes. You can have a level 60 player fully geared and ready to go.

**Comment by robinsch** [comment]
You can use this in the script, point here is using diffrent templateEntry. e.g. level 60 / 65 / 70 gear for each spec.

**Comment by DevDaemon** [comment]
Ok I see.

**Pull request merged**
