### PR TITLE
Core/Template: Implement Enchant and Gem into ItemTemplate. Implement SpellTemplate. Implement ReputationTemplate.

### PR DESCRIPTION
**Pull request by robinsch**
EnchantEntry is taken from SPELL_EFFECT_ENCHANT_ITEM EffectMiscValueA
GemEnchantEntry is taken from GemPropertiesEntry

### CODE REVIEW

**Comment by robinsch** [comment]
Updated: map to unordered_map

**Comment by DevDaemon** [comment]
And also you could use a vector of ItemTemplate instead of a vector of ItemTemplate* if you are doing optimizations.

**Comment by robinsch** [comment]
Done, anything else?

**Comment by robinsch** [comment]
Drop Primary Key to support same item with different enchants (2x One-Handed Weapons with same ItemEntry and different EnchantEntry)
Add support for Spell Template.
Drop Singleton but ensure that only one instance is active.

**Pull request merged**
